
services:
  rvc-invoices-bot:
    build: .
    container_name: rvc-invoices-bot
    restart: always
    env_file:
      - .env
    volumes:
      - invoices_data:/app/data
      - invoices_logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  invoices_data:
  invoices_logs:
